### ISSUE TITLE
+Z face not writing?

### ISSUE THREAD

**Issue by meshula** [dariomanesku/cmft#1]
Thanks for releasing the cmft program!

I wrote a beckmann-phong convolver for OpenEXR's envmap program 
(https://github.com/meshula/openexr/tree/master/OpenEXR/exrenvmap2)

but I am preferring cmft, because of it's greater variety of options and fantastic speed.

I'm running into an issue though, have you seen an issue with the +Z face not writing?

Here is my input file, slightly modified from your sample.

  eval $CMFT $@ --input "kula1.tga"           \
              ::Filter options                  \
              --filter radiance                 \
              --srcFaceSize 256                 \
              --excludeBase false               \
              --mipCount 9                      \
              --glossScale 10                   \
              --glossBias 1                     \
              --lightingModel phongbrdf         \
              --dstFaceSize 256                 \
              ::Processing devices              \
              --numCpuProcessingThreads 4       \
              --useOpenCL true                  \
              --clVendor anyGpuVendor           \
              --deviceType gpu                  \
              --deviceIndex 0                   \
              ::Aditional operations            \
              --inputGammaNumerator 1.0         \
              --inputGammaDenominator 1.0       \
              --outputGammaNumerator 1.0        \
              --outputGammaDenominator 1.0      \
              --generateMipChain false          \
              ::Output                          \
              --outputNum 3                     \
              --output0 "okretnica_pmrem"       \
              --output0params tga,bgra8,cubecross \
              --output1 "okretnica_pmrem"       \
              --output1params ktx,rgba8,cubemap \
              --output2 "okretnica_pmrem" \
              --output2params hdr,rgbe,hstrip

Here is the output. Hstrip also lacks +z. I tried a few different formats, all of them are missing the +z face.

![okretnica_pmrem](https://cloud.githubusercontent.com/assets/501238/3445337/7e040196-0136-11e4-9615-ee6bb74d3726.jpg)

**Comment by justinsaunders** [comment]
Hey - I'm hitting these timeouts too, they're easy to see in the output window - when the face is computed suspiciously fast :-D

CMFT info: Radiance ->  <GPU>  |    4 |   4.155s |  73.560s
CMFT info: Radiance ->  <GPU>  |    4 |   2.308s |  75.870s
CMFT info: Radiance ->  <GPU>  |    4 |   3.089s |  78.959s
CMFT info: Radiance ->  <GPU>  |    4 |   0.001s |  78.960s
CMFT info: Radiance ->  <GPU>  |    4 |   0.000s |  78.961s
CMFT info: Radiance ->  <GPU>  |    4 |   0.000s |  78.962s
CMFT info: Radiance ->  <GPU>  |    2 |   0.001s |  78.965s
CMFT info: Radiance ->  <GPU>  |    2 |   0.000s |  78.965s
CMFT info: Radiance ->  <GPU>  |    2 |   0.001s |  78.966s
CMFT info: Radiance ->  <GPU>  |    2 |   0.001s |  78.967s
CMFT info: Radiance ->  <GPU>  |    2 |   0.001s |  78.967s
CMFT info: Radiance ->  <GPU>  |    2 |   0.001s |  78.968s
CMFT info: Radiance ->  <GPU>  |    1 |   0.001s |  78.969s
CMFT info: Radiance ->  <GPU>  |    1 |   0.001s |  78.970s
CMFT info: Radiance ->  <GPU>  |    1 |   0.001s |  78.972s
CMFT info: Radiance ->  <GPU>  |    1 |   0.001s |  78.973s
CMFT info: Radiance ->  <GPU>  |    1 |   0.001s |  78.974s
CMFT info: Radiance ->  <GPU>  |    1 |   0.001s |  78.975s

Any updates on this?

**Comment by dariomanesku** [comment]
Try again after this: https://github.com/dariomanesku/cmft/commit/4a3a6fdcb743b35603bee62f75ff2a188216367d

**Comment by justinsaunders** [comment]
Thank you - which 'make' should I use to build VC projects on windows? (nmake doesn't work).
Do I need MinGW?
