### ISSUE TITLE
Is it possible to output DDS not in DX10 format ?

### ISSUE THREAD

**Issue by silvesthu** [dariomanesku/cmft#12]
Hello, 

I noticed that no matter input file is in DX10 format or not, output dds is always in DX10 format.
Which I found not able to be opened by "DirectX Texture Tool" within DirectX SDK, as well as some legacy library.
I wander if there is an option or some hint on modifying the source to achieve that ? 

I am aware that there is another issue discussing about similar problem.
At the moment it is a bit difficult here to add DX10 support for DDS loading.

Thank you for your marvelous work.

**Comment by dariomanesku** [comment]
It's not a big problem, you only need to modify this: https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L4729 according to your needs and that's it.

If you figure it out, feel free to contribute your changes back :)

**Comment by silvesthu** [comment]
Thank you so much ! I was afraid it would a time-consuming one.
