### ISSUE TITLE
Mipmaps are not saved for TGA output formats

### ISSUE THREAD

**Issue by ElArtista** [dariomanesku/cmft#18]
So, after using CmftStudio (fantastic work guys!) i decided to automate things a little by using its command line variant. Whereas the gui version saved the mipmaps in files of the form `'filename-<mipnum>-<resX>x<resY>.tga`, the command line version just writes the first mipmap while outputing this:

CMFT info: Saving out/indoors_rad.tga [TGA 1024x768 BGR8 HCross 1-faces 9-mips].
CMFT WARNING: Image seems to be containing more than one mip map. Only the first one will be saved due to the limits of TGA format.

The portion of the script that generates the radiance map is this:
```
%cmft% --input "%outd%/%~n1_cross.tga"   ^
       ::Filter options                  ^
       --filter radiance                 ^
       --srcFaceSize 256                 ^
       --excludeBase false               ^
       --mipCount 6                      ^
       --generateMipChain true           ^
       --glossScale 10                   ^
       --glossBias 3                     ^
       --lightingModel blinnbrdf         ^
       --edgeFixup none                  ^
       --dstFaceSize 256                 ^
       ::Processing devices              ^
       --numCpuProcessingThreads 4       ^
       --useOpenCL true                  ^
       --clVendor anyGpuVendor           ^
       --deviceType gpu                  ^
       --deviceIndex 0                   ^
       ::Aditional operations            ^
       --inputGammaNumerator 2.2         ^
       --inputGammaDenominator 1.0       ^
       --outputGammaNumerator 1.0        ^
       --outputGammaDenominator 2.2      ^
       ::Output                          ^
       --output0 "%outd%/%~n1_rad"       ^
       --output0params tga,bgr8,hcross

```

As far as i inspected the saving code the command line tool should be able to do this to:
https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L5218
So i am either missing some params, or the correct m_numMips does not reach the imageSave function i suppose.

**Comment by dariomanesku** [comment]
There are no 'guys', there's only me :)

I just tried on my machine and it works. Are you sure you have the latest source/build? Compile from source, provided binaries are outdated.

**Comment by ElArtista** [comment]
Well as it seems with the latest build it works as it should. Maybe it would be a good idea to update the executables in sync with the cmftStudio to avoid confusion :P
Thanks for helping!

**Comment by dariomanesku** [comment]
Good, I'm glad. :)
I put the builds there manually. Ideally, I would have a build system that does it automatically for me but I won't go into that now.

Cheers.
