### ISSUE TITLE
outputParams seem to be ignored

### ISSUE THREAD

**Issue by justinsaunders** [dariomanesku/cmft#20]
Using the commandline:
cmft.exe --input "MonValley_G_DirtRoad_3k.hdr" --filter radiance --lightingModel phongbrdf --outputNum 1 --output0 "test_rad" --outputParams ktx,rgba16,latlong

I expect an ktx file output in rgba16 format. However cmft says:

>Saving test_rad.dds [DDS 2160x1080 BGRA8 LatLong 1-faces 9-mips].

It seems the tool always outputs dds, BGRA8 - is this a known issue?

**Comment by dariomanesku** [comment]
It should be --output**0**Params instead of --outputParams.

**Comment by justinsaunders** [comment]
Yes, thank you, silly typo on my part.
