### ISSUE TITLE
Heap Corruption when creating RGB16F images?

### ISSUE THREAD

**Issue by simongeilfus** [dariomanesku/cmft#21]
It seems that the following code triggers a `Debug Error: HEAP CORRUPTION DETECTED` (at least it does in Visual Studio) :

``` c++
cmft::Image output;
cmft::imageCreate( output, 512, 512, 0x0, 1, 1, cmft::TextureFormat::RGB16F );
cmft::imageUnload( output );
```

I've not found the culprit yet, but could it have anything to do with the fact that [imageCreate assumes the texture format to have 4 channels](https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L1051-L1064)? The weird thing is that it also seems to be exclusive to RGB16F because other 3 channels formats I've tried don't seem to produce this error.

I'm doing some tests with application verifier and windbg but can't seem to find the leak yet (if there is any). I'll send a PR if I do find something!

**Comment by dariomanesku** [comment]
:+1:
