### ISSUE TITLE
Blurring RGBA32f Textures with Alpha != 1 ends with Artifacts

### ISSUE THREAD

**Issue by PeterMerkert** [dariomanesku/cmft#22]
Hi!

When blurring RGBA32f images which have "alpha corners" where alpha switches from 1.0f to 0.0f between two pixels, the blurring will be broken when running on the GPU.

All mip levels created on the GPU will have failed blurring. The ones on the CPU work fine.
Please see the attached picture for the resulting problem when having the alpha corners in the image.

![cmft_blurring_broken](https://cloud.githubusercontent.com/assets/4216454/19722090/0971658e-9b6d-11e6-8ad0-337f499aa9f8.png)

**Comment by dariomanesku** [comment]
I didn't reproduce the error but I guess I fixed it. Check it out.
