### ISSUE TITLE
DdsPixelFormat

### ISSUE THREAD

**Issue by rextimmy** [dariomanesku/cmft#23]
Hey i noticed this small problem, when getting the fourcc value here for BGR8 & BGRA8 https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L625-L626 it is using D3DFMT_R8G8B8 | D3DFMT_A8B8G8R8 . This is causing amd compressonator and nvidia dds photoshop plugin to not recognize the format.  Just checking with MS DxTex tool, it writes the fourcc for those two formats as 0. Doing this makes both amd compressonator and nvidia dds photoshop plugin to be able to read them.  Here is a link for MS one where they write the fourcc as 0 for those particular formats https://github.com/Microsoft/DirectXTex/blob/master/DirectXTex/DDS.h#L101-L102.

**Comment by dariomanesku** [comment]
Sorry, I somehow missed the notification for this.
At the moment I don't have those tools at hand to test it out. Hopefully it's good.

**Comment by rextimmy** [comment]
Ok sweet, seems to be working here all ok. If you have the old june 2010 directx sdk there is a tool called DxTex.exe you test it out with, also amd compress here http://developer.amd.com/tools-and-sdks/archive/games-cgi/amdcompress/ (open source now). Anyway thanks for cmft, i find it a very handy little app.

**Comment by dariomanesku** [comment]
Cool, I'm glad. :)

I'm on Linux most of the time and I'm using PVRTexTool. AMD Compress seems nice, I'll try it.
