### ISSUE TITLE
LatLong to cubemap

### ISSUE THREAD

**Issue by CarbonMan** [dariomanesku/cmft#25]
Not an issue as such more of a how do I...
I have an equirectangular image and would like to extract a cubemap as 6 separate images from it using cmft on the command line. It seems there would be a way to do it but I got lost in all the options.
Can you get me started?
Thanks.

**Comment by dariomanesku** [comment]
Yeah, I agree, cli interface could be simpler and more intuitive.
Here:
```
./cmft --input "okretnica.tga"            \
       --filter none                      \
       --outputNum 1                      \
       --output0 "okretnica_facelist"     \
       --output0params tga,bgra8,facelist
```
