### ISSUE TITLE
Errors in Windows .zip file 

### ISSUE THREAD

**Issue by embeh** [dariomanesku/cmft#26]
The .zip files containing the Windows binaries has an error, see attached screenshot
!

This is using 7-Zip 16.02 64bit for extraing the archive.

[ziperror](https://cloud.githubusercontent.com/assets/3431046/23807280/7728e15c-05c5-11e7-8d2c-4c3a3c304124.png)

**Comment by dariomanesku** [comment]
You should compile latest cmft from source, I don't maintain fresh builds.
