### ISSUE TITLE
Causing Maya crashed when importing dds image generated from cmft

### ISSUE THREAD

**Issue by xu-xionglong** [dariomanesku/cmft#45]
I use this tool to generated a mipmap chain for my irradiance map, and exported as a single DDS file, which can be viewed correctly in pvrTexTool. However, when I try to import the DDS image into Maya, the program crashed immediately. Is there any solution?

**Comment by dariomanesku** [comment]
You can try to re-export DDS from PvrTexTool.

**Comment by xu-xionglong** [comment]
Thanks. But it seems that it is a bug in some version of Maya.
