### ISSUE TITLE
Saving to RGBA32F outputs DXT1?

### ISSUE THREAD

**Issue by vorg** [dariomanesku/cmft#7]
I'm trying to save 32f HDR CubeMap with `dds,rgba32f,cubemap` and get the message 

```
Saving GracieReflection3 [DDS 256x256 RGBA32F Cubemap 6-faces 9-mips].
```

But the resulting file has FOURCC code of `808540228` which is DXT1. Shouldn't `RGBA32F` be RAW data?

My config tested both on OSX and Win

```
eval $CMFT $@ --input "grace_cross.hdr"           \
              --filter radiance               \
              --srcFaceSize 256                   \
              --dstFaceSize 256                   \
              --excludeBase false               \
              --mipCount 9                      \
              --glossScale 10                   \
              --glossBias 1                     \
              --lightingModel phongbrdf         \
              --useOpenCL false                 \
              --numCpuProcessingThreads 4       \
              --inputGammaNumerator 1.0         \
             --inputGammaDenominator 1.0       \
             --outputGammaNumerator 1.0        \
             --outputGammaDenominator 1.0      \
             --generateMipChain true          \
              --outputNum 1                     \
              --output0 "GracieReflection3"         \
              --output0params dds,rgba32f,cubemap
```

**Comment by dariomanesku** [comment]
PVRTexTool opens dds,rgba32f,cubemap from cmft without problem.
Here is where is that FOURCC from:
1. https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L601
2. https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L591 (third param)
3. https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L469

The documentation says:
- Any DXGI format  |  DDS_FOURCC  |  "DX10"  // from: http://msdn.microsoft.com/en-us/library/windows/desktop/bb943991(v=vs.85).aspx
- DXGI_FORMAT_R32G32B32A32_FLOAT = 2 // from DXGI enumeration here: http://msdn.microsoft.com/en-us/library/windows/desktop/bb173059(v=vs.85).aspx

I haven't gone very deep into documentation but my guess is: you can save DDS in two ways, using legacy format codes or using DX10 header extension. If you go the DX10 way than FOURCC is "DX10" (808540228) and the format is specified in the dx10 header:
1. https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L786
2. https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L790
3. https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L604

If you are loading the *.dds image in your code, check how it is done here:
https://github.com/dariomanesku/cmft/blob/master/src/cmft/image.cpp#L3571
I'm not saying it is 100% correct or that matches the specification, but it does successfully load all dds images i tried.

**Comment by vorg** [comment]
You right, adding support for DX10 header solved the issue. Thanks!

**Comment by dariomanesku** [comment]
:+1:
